packages:
  - apps/*
  - packages/*

catalog:
  '@vitejs/plugin-react': 6.1.0
  react: 19.2.8
  react-dom: 19.2.8
  typescript: 7.0.2
  vite: 8.2.2
  zod: 4.4.3

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - react@19.2.8
  - react-dom@19.2.8
  - typescript@7.0.2
  - vite@8.2.2
  - '@vitejs/plugin-react@6.1.0'
  - zod@4.4.3
